table _Metrics
	lineageTag: 86d3aa75-f888-4412-a5ae-c6c155a91684

	measure 'Activity Count' =
			
			DISTINCTCOUNT(strava_activities[Activity Id])
		formatString: #,0
		lineageTag: ac70a1f0-1205-4da5-b527-4538b8406c96

	measure 'Total Distance (mi)' =
			
			SUM(strava_activities[Distance (mi)])
		lineageTag: 11857153-0078-4534-b69e-0f3df1559f09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Time Spent (Hours)' = SUM(strava_activities[Elapsed Time (sec)])/3600
		lineageTag: fe604751-0f4c-495c-9382-52dc9d255f04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg. Pace' = ```
			
			VAR TotalTimeSec = SUM('strava_activities'[Moving Time (sec)])
			VAR TotalDistance = SUM('strava_activities'[Distance (mi)])
			VAR AvgPaceSec = DIVIDE(TotalTimeSec, TotalDistance)
			
			RETURN
			    FORMAT(
			        TIME(0, INT(DIVIDE(AvgPaceSec, 60)), MOD(AvgPaceSec, 60)),
			        "nn:ss"
			    )
			
			```
		lineageTag: ae83f7cf-b38b-4471-b73a-db0728ee07cd

	measure 'Workout Mileage %' =
			
			CALCULATE(
			    [Total Distance (mi)],
			        'Workout Type'[Workout Type] = "Workout"
			)
			/
			[Total Distance (mi)]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e6edd21c-329f-4b73-bac0-a2f807f07a3f

	partition _Metrics = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

