table strava_activities
	lineageTag: 25e55b73-24e9-4512-964b-f023c1f4aa6f

	column athlete
		dataType: string
		lineageTag: 524b77c9-8497-4b87-8902-c7ba77436192
		summarizeBy: none
		sourceColumn: athlete

		annotation SummarizationSetBy = User

	column 'Activity Name'
		dataType: string
		lineageTag: e5d1c168-de1e-49ce-bc81-a30fa7dbd8f2
		summarizeBy: none
		sourceColumn: Activity Name

		annotation SummarizationSetBy = User

	column 'Distance (m)'
		dataType: double
		lineageTag: 0a52219d-a879-4c9e-a511-dbb921ed4b4b
		summarizeBy: none
		sourceColumn: Distance (m)

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Moving Time (sec)'
		dataType: int64
		formatString: 0
		lineageTag: 74d9f5fa-d722-4bb3-8914-0b78bdbc9b28
		summarizeBy: none
		sourceColumn: Moving Time (sec)

		annotation SummarizationSetBy = User

	column 'Elapsed Time (sec)'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e7406628-2e06-483b-88fd-3ecf9ffe1f88
		summarizeBy: none
		sourceColumn: Elapsed Time (sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column total_elevation_gain
		dataType: double
		lineageTag: 082695ed-630b-4932-a405-73570ec5febe
		summarizeBy: none
		sourceColumn: total_elevation_gain

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Activity Type'
		dataType: string
		lineageTag: 72676153-a2e4-4651-a701-441fddb3d167
		summarizeBy: none
		sourceColumn: Activity Type

		annotation SummarizationSetBy = User

	column 'Activity Id'
		dataType: int64
		formatString: 0
		lineageTag: 20bbc30f-f8d7-4c00-b015-39ec817f7034
		summarizeBy: none
		sourceColumn: Activity Id

		annotation SummarizationSetBy = User

	column 'Start Date (Local)'
		dataType: dateTime
		formatString: General Date
		lineageTag: d0f9fbf4-44ce-46cf-aaf3-3d5391877df2
		summarizeBy: none
		sourceColumn: Start Date (Local)

		variation Variation
			isDefault
			relationship: e0330078-1cc4-48dc-bd4a-3c40df95cd6a
			defaultHierarchy: LocalDateTable_586965cd-d908-441a-987b-2111ac5778fd.'Date Hierarchy'

		annotation SummarizationSetBy = User

	column timezone
		dataType: string
		lineageTag: a689d9ff-4d74-406b-b8c2-f5bf884c3add
		summarizeBy: none
		sourceColumn: timezone

		annotation SummarizationSetBy = User

	column utc_offset
		dataType: int64
		formatString: 0
		lineageTag: 3017dc7b-c3e4-465e-94fe-2506cd38d9cf
		summarizeBy: none
		sourceColumn: utc_offset

		annotation SummarizationSetBy = User

	column location_city
		dataType: string
		lineageTag: 5c67e7f7-671f-48ce-ad02-1f444bd803fa
		summarizeBy: none
		sourceColumn: location_city

		annotation SummarizationSetBy = User

	column location_state
		dataType: string
		lineageTag: 0493c910-09da-4d26-a7f1-bd0cc03abee1
		summarizeBy: none
		sourceColumn: location_state

		annotation SummarizationSetBy = User

	column location_country
		dataType: string
		lineageTag: b33e028c-35df-4394-b927-ea1b5767f3f8
		summarizeBy: none
		sourceColumn: location_country

		annotation SummarizationSetBy = User

	column 'Kudos Count'
		dataType: int64
		formatString: 0
		lineageTag: c73a4421-96a3-483e-9f7c-24abab09ae48
		summarizeBy: none
		sourceColumn: Kudos Count

		annotation SummarizationSetBy = User

	column 'Comment Count'
		dataType: int64
		formatString: 0
		lineageTag: c18f210c-72e4-425f-b697-2e729cadc234
		summarizeBy: none
		sourceColumn: Comment Count

		annotation SummarizationSetBy = User

	column photo_count
		dataType: int64
		formatString: 0
		lineageTag: 7e13c655-1b00-4784-af81-ab477935ec9c
		summarizeBy: none
		sourceColumn: photo_count

		annotation SummarizationSetBy = User

	column private
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 371995a1-77e3-4d48-bbab-ea577655523f
		summarizeBy: none
		sourceColumn: private

		annotation SummarizationSetBy = User

	column visibility
		dataType: string
		lineageTag: 7b043c0e-b04f-40af-92ef-f16c3d3c505b
		summarizeBy: none
		sourceColumn: visibility

		annotation SummarizationSetBy = User

	column flagged
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e1c64338-47e3-460d-be3a-642c83427f0c
		summarizeBy: none
		sourceColumn: flagged

		annotation SummarizationSetBy = User

	column 'Average Heartrate'
		dataType: double
		lineageTag: 609ee5e8-f9bc-4b34-b55b-92bfacaf011d
		summarizeBy: none
		sourceColumn: Average Heartrate

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Max Heartrate'
		dataType: int64
		formatString: 0
		lineageTag: 7fac0c01-ee32-482b-ac8a-31f39cdcdcbc
		summarizeBy: none
		sourceColumn: Max Heartrate

		annotation SummarizationSetBy = User

	column elev_high
		dataType: double
		lineageTag: 24068538-5065-43f5-9a6b-844285ba4cd6
		summarizeBy: none
		sourceColumn: elev_high

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column elev_low
		dataType: double
		lineageTag: 7ded0724-2dda-48f3-9c06-f7cb41426293
		summarizeBy: none
		sourceColumn: elev_low

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Suffer Score'
		dataType: int64
		formatString: 0
		lineageTag: 407744a8-ec51-4425-ae85-ddeb5e811310
		summarizeBy: none
		sourceColumn: Suffer Score

		annotation SummarizationSetBy = User

	column workout_type
		dataType: double
		formatString: 0
		lineageTag: f6154c21-a26d-47f6-a6fc-6e5464e3a9fc
		summarizeBy: none
		sourceColumn: workout_type

		annotation SummarizationSetBy = User

	column average_cadence
		dataType: double
		lineageTag: f8a97277-37dd-4589-825d-0d88aecef818
		summarizeBy: none
		sourceColumn: average_cadence

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Start Lat'
		dataType: string
		lineageTag: a190c6cf-16a3-4f3b-a3fc-6830b5b9ef56
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: Start Lat

		annotation SummarizationSetBy = User

	column 'Start Long'
		dataType: string
		lineageTag: 8be1ab12-0345-45a4-94a6-3e3226a47fa0
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: Start Long

		annotation SummarizationSetBy = User

	column 'Web Link to Activity' = "https://www.strava.com/activities/" & strava_activities[Activity Id]
		lineageTag: 927d5d86-b4e3-46ca-9ef7-c115c021b4ba
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Elapsed Time' = FORMAT(TIME(0, 0, strava_activities[Elapsed Time (sec)]), "HH:mm:ss")
		lineageTag: 836fc3b0-87ba-4281-9d38-4adbe6849032
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Distance (mi)' = strava_activities[Distance (m)] * 0.000621371
		formatString: 0.00
		lineageTag: 0ca841f6-7ec5-44b5-bbd3-713127c610f1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Local Start Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: adc9db81-aa9c-4f53-ae19-16da766562c9
		summarizeBy: none
		sourceColumn: Local Start Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Polyline
		dataType: string
		lineageTag: d42f8eef-065e-4d8c-8b1a-a8f6ca7d8fd6
		summarizeBy: none
		sourceColumn: Polyline

		annotation SummarizationSetBy = Automatic

	column 'Week Sort' = ```
			
			YEAR(strava_activities[Start Date (Local)]) * 100 + WEEKNUM(strava_activities[Start Date (Local)], 2)
			
			```
		formatString: 0
		lineageTag: 30a5f597-6cf8-422f-b229-c2b5c8d3adc2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Race Distance' = ```
			
			IF(
			    RELATED('Workout Type'[Workout Type]) = "Race", 
			    SWITCH(
			        TRUE(),
			        strava_activities[Distance (mi)] >= 0.9 && strava_activities[Distance (mi)] <= 1.1, "1 Mile",
			        strava_activities[Distance (mi)] >= 2.8 && strava_activities[Distance (mi)] <= 3.4, "5K",
			        strava_activities[Distance (mi)] >= 5.6 && strava_activities[Distance (mi)] <= 6.8, "10K",
			        strava_activities[Distance (mi)] >= 4.5 && strava_activities[Distance (mi)] <= 5.5, "5 Mile",
			        strava_activities[Distance (mi)] >= 9 && strava_activities[Distance (mi)] <= 11, "10 Mile",
			        strava_activities[Distance (mi)] >= 11.8 && strava_activities[Distance (mi)] <= 14.3, "Half Marathon",
			        strava_activities[Distance (mi)] >= 23.6 && strava_activities[Distance (mi)] <= 28.8, "Full Marathon",
			        "Unknown"
			    ),
			    "Not a Race"
			)
			
			```
		lineageTag: 00d21723-c8a9-426d-a76d-b1c50c858590
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Date = strava_activities[Start Date (Local)].[Date]
		formatString: Long Date
		lineageTag: 69f99749-3f27-479e-9526-0fdbda06c870
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Moving Time' = FORMAT(TIME(0, 0, strava_activities[Moving Time (sec)]), "HH:mm:ss")
		lineageTag: 1c4a0add-3704-40ce-8600-c88560f8070b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition strava_activities = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Strava-Stream-\strava_activities.csv"),[Delimiter=",", Columns=55, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"resource_state", Int64.Type}, {"athlete", type text}, {"name", type text}, {"distance", type number}, {"moving_time", Int64.Type}, {"elapsed_time", Int64.Type}, {"total_elevation_gain", type number}, {"type", type text}, {"sport_type", type text}, {"id", Int64.Type}, {"start_date", type datetime}, {"start_date_local", type datetime}, {"timezone", type text}, {"utc_offset", Int64.Type}, {"location_city", type text}, {"location_state", type text}, {"location_country", type text}, {"achievement_count", Int64.Type}, {"kudos_count", Int64.Type}, {"comment_count", Int64.Type}, {"athlete_count", Int64.Type}, {"photo_count", Int64.Type}, {"map", type text}, {"trainer", type logical}, {"commute", type logical}, {"manual", type logical}, {"private", type logical}, {"visibility", type text}, {"flagged", type logical}, {"gear_id", type text}, {"start_latlng", type text}, {"end_latlng", type text}, {"average_speed", type number}, {"max_speed", type number}, {"has_heartrate", type logical}, {"average_heartrate", type number}, {"max_heartrate", Int64.Type}, {"heartrate_opt_out", type logical}, {"display_hide_heartrate_option", type logical}, {"elev_high", type number}, {"elev_low", type number}, {"upload_id", Int64.Type}, {"upload_id_str", Int64.Type}, {"external_id", type text}, {"from_accepted_tag", type logical}, {"pr_count", Int64.Type}, {"total_photo_count", Int64.Type}, {"has_kudoed", type logical}, {"suffer_score", Int64.Type}, {"workout_type", Int64.Type}, {"average_cadence", type number}, {"average_watts", type number}, {"device_watts", type logical}, {"kilojoules", Int64.Type}, {"average_temp", type text}}),
				    #"Inserted Text Between Delimiters" = Table.AddColumn(#"Changed Type", "Start Lat", each Text.BetweenDelimiters([start_latlng], "[", ","), type text),
				    #"Inserted Text Between Delimiters1" = Table.AddColumn(#"Inserted Text Between Delimiters", "Start Long", each Text.BetweenDelimiters([start_latlng], " ", "]"), type text),
				    #"Replaced Value" = Table.ReplaceValue(#"Inserted Text Between Delimiters1","]","",Replacer.ReplaceText,{"Start Lat"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"name", "Activity Name"}, {"type", "Activity Type"}, {"comment_count", "Comment Count"}, {"id", "Activity Id"}, {"kudos_count", "Kudos Count"}, {"distance", "Distance (m)"}, {"elapsed_time", "Elapsed Time (sec)"}, {"start_date_local", "Start Date"}, {"start_date", "Start Date (Local)"}}),
				    #"Inserted Start of Hour" = Table.AddColumn(#"Renamed Columns", "Start of Hour", each Time.StartOfHour([#"Start Date (Local)"]), type datetime),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Start of Hour",{{"Start of Hour", type time}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"Start of Hour", "Local Start Time"}, {"average_heartrate", "Average Heartrate"}, {"max_heartrate", "Max Heartrate"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"trainer", "commute", "has_heartrate", "heartrate_opt_out", "display_hide_heartrate_option", "upload_id", "upload_id_str", "external_id", "from_accepted_tag", "total_photo_count", "has_kudoed", "average_watts", "device_watts", "kilojoules", "average_temp"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"suffer_score", "Suffer Score"}}),
				    #"Inserted Text Between Delimiters2" = Table.AddColumn(#"Renamed Columns2", "Polyline", each Text.BetweenDelimiters([map], "'", "'", 6, 0), type text),
				    #"Removed Other Columns" = Table.SelectColumns(#"Inserted Text Between Delimiters2",{"athlete", "Activity Name", "Distance (m)", "moving_time", "Elapsed Time (sec)", "total_elevation_gain", "Activity Type", "Activity Id", "Start Date (Local)", "Start Date", "timezone", "utc_offset", "location_city", "location_state", "location_country", "Kudos Count", "Comment Count", "photo_count", "private", "visibility", "flagged", "average_cadence", "Average Heartrate", "Max Heartrate", "elev_high", "elev_low", "Suffer Score", "workout_type", "Start Lat", "Start Long", "Local Start Time", "Polyline"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Removed Other Columns",{"Start Date"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns1", each ([Activity Type] = "Run")),
				    #"Replaced Value1" = Table.ReplaceValue(#"Filtered Rows",null,0,Replacer.ReplaceValue,{"workout_type"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",2,0,Replacer.ReplaceValue,{"workout_type"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Replaced Value2",{{"moving_time", "Moving Time (sec)"}})
				in
				    #"Renamed Columns3"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

